In [113]:
import pandas as pd
import numpy as np

# Loading Data

In [114]:
df = pd.read_csv("global_ai_jobs.csv")

In [115]:
df.shape

(90000, 35)

In [116]:
df.columns

Index(['id', 'country', 'job_role', 'ai_specialization', 'experience_level',
       'experience_years', 'salary_usd', 'bonus_usd', 'education_required',
       'industry', 'company_size', 'interview_rounds', 'year', 'work_mode',
       'weekly_hours', 'company_rating', 'job_openings',
       'hiring_difficulty_score', 'layoff_risk', 'ai_adoption_score',
       'company_funding_billion', 'economic_index', 'ai_maturity_years',
       'offer_acceptance_rate', 'tax_rate_percent', 'vacation_days',
       'skill_demand_score', 'automation_risk', 'job_security_score',
       'career_growth_score', 'work_life_balance_score', 'promotion_speed',
       'salary_percentile', 'cost_of_living_index', 'employee_satisfaction'],
      dtype='object')

In [117]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90000 entries, 0 to 89999
Data columns (total 35 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       90000 non-null  int64
 1   country                  90000 non-null  object
 2   job_role                 90000 non-null  object
 3   ai_specialization        90000 non-null  object
 4   experience_level         90000 non-null  object
 5   experience_years         90000 non-null  int64
 6   salary_usd               90000 non-null  int64
 7   bonus_usd                90000 non-null  int64
 8   education_required       90000 non-null  object
 9   industry                 90000 non-null  object
 10  company_size             90000 non-null  object
 11  interview_rounds         90000 non-null  int64
 12  year                     90000 non-null  int64
 13  work_mode                90000 non-null  object
 14  weekly_hours             90000 non-null  float64
 15  company_rating           90000 non-null  float64
 16  job_openings             90000 non-null  int64
 17  hiring_difficulty_score  90000 non-null  float64
 18  layoff_risk              90000 non-null  float64
 19  ai_adoption_score        90000 non-null  int64
 20  company_funding_billion  90000 non-null  float64
 21  economic_index           90000 non-null  float64
 22  ai_maturity_years        90000 non-null  int64
 23  offer_acceptance_rate    90000 non-null  float64
 24  tax_rate_percent         90000 non-null  float64
 25  vacation_days            90000 non-null  int64
 26  skill_demand_score       90000 non-null  int64
 27  automation_risk          90000 non-null  int64
 28  job_security_score       90000 non-null  int64
 29  career_growth_score      90000 non-null  int64
 30  work_life_balance_score  90000 non-null  int64
 31  promotion_speed          90000 non-null  int64
 32  salary_percentile        90000 non-null  int64
 33  cost_of_living_index     90000 non-null  float64
 34  employee_satisfaction    90000 non-null  int64
dtypes: float64(9), int64(18), object(8)
memory usage: 24.0+ MB

In [118]:
df.rename(columns = {'salary_usd' : 'salary','bonus_usd' : 'bonus'},inplace = True)

In [119]:
df.head(2)

,id,country,job_role,ai_specialization,experience_level,experience_years,salary,bonus,education_required,industry,...,vacation_days,skill_demand_score,automation_risk,job_security_score,career_growth_score,work_life_balance_score,promotion_speed,salary_percentile,cost_of_living_index,employee_satisfaction
0,1,UAE,Machine Learning Engineer,Reinforcement Learning,Entry,0,66465,5395,Master,Automotive,...,27,12,76,57,65,73,15,55,1.23,76
1,2,USA,AI Engineer,LLM,Entry,1,75507,11713,Bootcamp,Retail,...,27,54,29,69,60,51,15,58,0.87,67

# Cleaning Data

In [120]:
columns_to_drop = ['id',
    "salary_percentile"
]

In [121]:
df.drop(columns = columns_to_drop,axis = 1,inplace = True)

# Checking Duplicates

In [122]:
df.duplicated().sum()

0

# Checking Null

In [123]:
df.isnull().sum()

country                    0
job_role                   0
ai_specialization          0
experience_level           0
experience_years           0
salary                     0
bonus                      0
education_required         0
industry                   0
company_size               0
interview_rounds           0
year                       0
work_mode                  0
weekly_hours               0
company_rating             0
job_openings               0
hiring_difficulty_score    0
layoff_risk                0
ai_adoption_score          0
company_funding_billion    0
economic_index             0
ai_maturity_years          0
offer_acceptance_rate      0
tax_rate_percent           0
vacation_days              0
skill_demand_score         0
automation_risk            0
job_security_score         0
career_growth_score        0
work_life_balance_score    0
promotion_speed            0
cost_of_living_index       0
employee_satisfaction      0
dtype: int64

# Job Market Overview

In [124]:
df['job_count'] = 1

In [125]:
df['jobs_in_country'] = df.groupby('country')['job_count'].transform('sum')

In [126]:
df[['country','jobs_in_country']].drop_duplicates().sort_values('jobs_in_country',ascending = False)

        country  jobs_in_country
24       Canada             7602
8     Australia             7589
11    Singapore             7583
2        Brazil             7545
26           UK             7532
0           UAE             7529
12  Netherlands             7514
4       Germany             7461
3         India             7450
10       France             7440
1           USA             7405
6         Japan             7350

In [128]:
# Insights : AI jobs varies narrowly ranging from 7350 to 7602 across countries. Canada reports the highest number of job roles,while Japan the lowest.

In [129]:
df['jobs_in_industry'] = df.groupby('industry')['job_count'].transform('sum')

In [130]:
df[['industry','jobs_in_industry']].drop_duplicates().sort_values('jobs_in_industry',ascending = False)

      industry  jobs_in_industry
12      Gaming              9190
24   Education              9067
26     Finance              9057
11      Energy              9017
1       Retail              8987
3         Tech              8984
7   Consulting              8954
9      Telecom              8939
0   Automotive              8930
2   Healthcare              8875

In [131]:
# Insights : Gaming & Education industry leads the ai job market hiring while automative & Healthcare industry are trailing

In [132]:
df['jobs_in_role'] = df.groupby('job_role')['job_count'].transform('sum')

In [133]:
df[['job_role','jobs_in_role']].drop_duplicates().sort_values('jobs_in_role',ascending = False)

                     job_role  jobs_in_role
8                NLP Engineer         11412
3        Software Engineer AI         11333
2          Research Scientist         11309
0   Machine Learning Engineer         11263
1                 AI Engineer         11247
7    Computer Vision Engineer         11227
13             Data Scientist         11146
6                Data Analyst         11063

In [138]:
# Insights : All roles relatively have uniform range of job count varies from 11063 to 11412,indicating demand is evenly distributed across AI job
# market. NLP Engineers reports the highest number of job count, while Data Analysts the lowest.

In [139]:
df['jobs_in_company'] = df.groupby('company_size')['job_count'].transform('sum')

In [140]:
df[['company_size','jobs_in_company']].drop_duplicates().sort_values('jobs_in_company',ascending = False)

  company_size  jobs_in_company
4       Medium            18328
5      Startup            18008
9   Enterprise            17988
0        Small            17919
2        Large            17757

In [141]:
# Insights : Job counts are relatively uniform across company sizes(17757-18328).Medium sized companies reports the highest number of jobs , while Large 
# companies the lowest.

In [142]:
df.to_csv('job_market_overview.csv',index = False)

# Salary Intellegence

In [143]:
df['real_salary'] = df['salary']/df['cost_of_living_index']

In [144]:
df['salary_country_avg'] = df.groupby('country')['salary'].transform('mean').round(2)

In [145]:
salary_by_country = df.groupby('country')['salary'].mean().round(2).sort_values(ascending = False)

In [146]:
salary_by_country

country
USA            132995.21
Singapore      116954.73
Australia      110549.81
Canada         108671.05
UK             102826.24
Netherlands    102379.05
Germany        100007.78
Japan           98507.66
France          95170.46
UAE             93507.70
Brazil          53704.84
India           43106.30
Name: salary, dtype: float64

In [147]:
# Insights : Developed countries such as USA & Singapore offer significantly higher salaries 
# while the emerging countries like India & Brazil lag behind.

In [148]:
df['realsalary_by_country'] = df.groupby('country')['real_salary'].transform('mean').round(2)

In [149]:
real_salary_by_country = df.groupby('country')['real_salary'].mean().round(2).sort_values(ascending = False)

In [150]:
real_salary_by_country

country
USA            106759.92
Singapore       94247.98
Australia       88193.03
Canada          86785.86
Netherlands     82648.59
UK              81992.69
Germany         80058.54
Japan           78710.09
France          76711.62
UAE             75717.85
Brazil          43016.20
India           34658.32
Name: real_salary, dtype: float64

In [151]:
df['salary_by_experience'] = df.groupby('experience_level')['salary'].transform('mean').round(2)

In [152]:
salary_vs_exp = df.groupby('experience_level')['salary'].mean().round(2).sort_values(ascending = False)
salary_vs_exp

experience_level
Lead      142318.95
Senior    104608.04
Mid        77411.91
Entry      61327.59
Name: salary, dtype: float64

In [153]:
# Insights : Salaries increase significantly with experience, with the largest jump observed between mid and senior level

In [154]:
df['salary_by_specialization'] = df.groupby('ai_specialization')['salary'].transform('mean').round(2)

In [155]:
salary_vs_specialization = df.groupby('ai_specialization')['salary'].mean().round(2).sort_values(ascending = False)

In [156]:
salary_vs_specialization

ai_specialization
Generative AI             97096.78
LLM                       97076.65
Analytics                 96905.55
MLOps                     96742.07
Computer Vision           96655.16
NLP                       96443.81
Forecasting               96010.56
Reinforcement Learning    95423.81
Name: salary, dtype: float64

In [157]:
# Insight : AI specialization show relatively similar range,with only marginal difference between domains.

In [158]:
df['salary_in_company_size'] = df.groupby("company_size")['salary'].transform('mean').round(2)

In [159]:
salary_in_company = df.groupby("company_size")['salary'].mean().round(2).sort_values(ascending = False)
salary_in_company

company_size
Medium        97322.58
Startup       96544.29
Small         96391.29
Enterprise    96308.77
Large         96143.88
Name: salary, dtype: float64

In [160]:
# Insights : Medium & Startup company pays the most while Largest company the lowest

In [161]:
df[['salary','skill_demand_score']].corr()

                      salary  skill_demand_score
salary              1.000000            0.001087
skill_demand_score  0.001087            1.000000

In [162]:
# Insights : Correlation between skill demand and salary is very weak, suggesting that salary is influence by other
# factors such as role, specialization, experience level and company size.

In [163]:
df.to_csv('salary_intellegence.csv', index = False)

#  Career Growth Analysis

In [164]:
# How AI careers evolve over time and which paths are most rewarding

In [165]:
salary_growth = df.groupby('experience_level')['salary'].mean().round(2).sort_values(ascending = False)
salary_growth

experience_level
Lead      142318.95
Senior    104608.04
Mid        77411.91
Entry      61327.59
Name: salary, dtype: float64

In [166]:
# Insights  :  Salary increases significanly with experience , longest jump is observed between Mid & Senior level

In [167]:
spec_growth = df.groupby(['ai_specialization','experience_level'])['salary'].mean().round(2).reset_index(name = 'mean_salary')

In [168]:
spec_growth['rank'] = spec_growth.groupby('experience_level')['mean_salary'].rank(method = 'dense',ascending = False)

In [169]:
spec_growth.sort_values(['experience_level','rank'],ascending = True)

         ai_specialization experience_level  mean_salary  rank
0                Analytics            Entry     61859.60   1.0
4          Computer Vision            Entry     61530.52   2.0
12           Generative AI            Entry     61486.32   3.0
8              Forecasting            Entry     61330.94   4.0
24                     NLP            Entry     61236.47   5.0
20                   MLOps            Entry     61145.08   6.0
16                     LLM            Entry     61094.07   7.0
28  Reinforcement Learning            Entry     60946.20   8.0
13           Generative AI             Lead    144657.03   1.0
21                   MLOps             Lead    142946.22   2.0
1                Analytics             Lead    142775.48   3.0
17                     LLM             Lead    141876.88   4.0
5          Computer Vision             Lead    141837.93   5.0
9              Forecasting             Lead    141785.68   6.0
25                     NLP             Lead    141338.09   7.0
29  Reinforcement Learning             Lead    141263.13   8.0
2                Analytics              Mid     78520.61   1.0
22                   MLOps              Mid     78011.66   2.0
26                     NLP              Mid     77839.88   3.0
30  Reinforcement Learning              Mid     77204.37   4.0
18                     LLM              Mid     77145.39   5.0
6          Computer Vision              Mid     77024.52   6.0
10             Forecasting              Mid     77003.74   7.0
14           Generative AI              Mid     76512.82   8.0
19                     LLM           Senior    106350.34   1.0
27                     NLP           Senior    104925.72   2.0
3                Analytics           Senior    104794.04   3.0
11             Forecasting           Senior    104645.09   4.0
23                   MLOps           Senior    104425.37   5.0
15           Generative AI           Senior    104209.52   6.0
7          Computer Vision           Senior    104026.18   7.0
31  Reinforcement Learning           Senior    103447.33   8.0

In [170]:
# Insights : At Entry & Medium level Analytics focused specialization offer the highest career growth .
# However at Senior levels, core AI specialization such as Generative AI,Mlops show the highest salaries, suggesting that deeper technical 
# expertise become more valuable with experience.

In [171]:
df['promotion_speed_industry'] = df.groupby('industry')['promotion_speed'].transform('mean').round(2)

In [172]:
df[['industry','promotion_speed_industry']].drop_duplicates().sort_values('promotion_speed_industry',ascending = False)

      industry  promotion_speed_industry
3         Tech                     38.66
2   Healthcare                     38.60
1       Retail                     38.59
7   Consulting                     38.51
26     Finance                     38.48
0   Automotive                     38.39
11      Energy                     38.35
12      Gaming                     38.35
24   Education                     38.33
9      Telecom                     38.15

In [173]:
# Insights : All industry offer relatively same range for promotion only marginal difference between industries.

In [174]:
df['satisfaction_by_exp'] = df.groupby('experience_level')['employee_satisfaction'].transform('mean').round(2)

In [175]:
df[['experience_level','satisfaction_by_exp']].drop_duplicates().sort_values('satisfaction_by_exp',ascending = False)

  experience_level  satisfaction_by_exp
7             Lead                78.36
3           Senior                74.61
5              Mid                70.75
0            Entry                67.13

In [176]:
# Insights : Employee satisfaction increases steadily with experience,rising from 67.13 at entry level to 78.36 at Lead level,
# indicating a positive association between experience and satisfaction.

In [177]:
df[['promotion_speed','layoff_risk']].corr()

                 promotion_speed  layoff_risk
promotion_speed         1.000000    -0.262194
layoff_risk            -0.262194     1.000000

In [178]:
# Insights : Employees who get promoted faster have slightly lower chances of being laid off, but the relationship is weak,
# so promotion speed alone doesn't guarantee job security.

In [179]:
df['workload_by_experience'] = df.groupby('experience_level')['weekly_hours'].transform('mean').round(2)

In [180]:
df[['experience_level','workload_by_experience']].drop_duplicates().sort_values('workload_by_experience',ascending = False)

  experience_level  workload_by_experience
5              Mid                   45.51
0            Entry                   45.49
3           Senior                   45.49
7             Lead                   45.42

In [181]:
# Insights : Workload remains consistent accross experience levels, ranging from 45.42 to 45.51.This suggest that experience levels 
# does not significantly influence workload.

In [182]:
df.to_csv('career_growth.csv',index = False)

# Job Stability & Risk Analysis

In [183]:
df['layoff_risk_in_industry'] = df.groupby('industry')['layoff_risk'].transform('mean').round(2)

In [184]:
layoff_risk_in_industry = df.groupby('industry')['layoff_risk'].mean().round(2).sort_values(ascending = False)

In [185]:
layoff_risk_in_industry

industry
Automotive    0.18
Consulting    0.18
Education     0.18
Energy        0.18
Finance       0.18
Gaming        0.18
Healthcare    0.18
Retail        0.18
Tech          0.18
Telecom       0.18
Name: layoff_risk, dtype: float64

In [186]:
# Insights : All industries exhibit the same layoff risk(0.18), indicating that layoff risk are driven by external factors like
# employee skill relevance, market condition and economic trends rather than industry specific dynamics.

In [187]:
df['automation_risk_in_role'] = df.groupby('job_role')['automation_risk'].transform('mean').round(2)

In [188]:
automation_risk_in_role = df.groupby('job_role')['automation_risk'].mean().round(2).sort_values(ascending = False)
automation_risk_in_role

job_role
Computer Vision Engineer     50.64
Software Engineer AI         50.62
Research Scientist           50.61
Data Analyst                 50.34
Data Scientist               50.22
NLP Engineer                 50.18
Machine Learning Engineer    50.15
AI Engineer                  50.09
Name: automation_risk, dtype: float64

In [189]:
# Insights : Automation risk is uniform accross all roles (~50), suggesting that automation impact is evenly distributes accross
# AI & data related roles.However,Computer Vision Engineer shows the highest risk(50.64) while AI Engineers have the lowest(50.09)

In [190]:
df[['salary','layoff_risk']].corr()

               salary  layoff_risk
salary       1.000000    -0.533439
layoff_risk -0.533439     1.000000

In [191]:
# Insigts : A moderare negative correlation between salary and layoff risk shows that higher paid roles tend to have slightly lower risk of
# layoffs.

In [192]:
df['job_security_in_role'] = df.groupby('job_role')['job_security_score'].transform('mean').round(2)

In [193]:
job_security = df.groupby('job_role')['job_security_score'].mean().round(2).sort_values(ascending = False)
job_security

job_role
Data Scientist               75.78
Software Engineer AI         75.67
Research Scientist           75.59
NLP Engineer                 75.53
AI Engineer                  75.51
Computer Vision Engineer     75.51
Machine Learning Engineer    75.48
Data Analyst                 75.45
Name: job_security_score, dtype: float64

In [194]:
# Insights : All job roles have uniform job security ranging from 75.78 to 75.45. However Data Scientists have the highest job security(~75.78)
# ,while Data Analyst have the lowest job security score (~75.45),indication minimal variations between roles.

In [195]:
df['risk_in_company'] = df.groupby('company_size')['layoff_risk'].transform('mean').round(2)

In [196]:
risk_in_company = df.groupby('company_size')['layoff_risk'].mean().round(2).sort_values(ascending = False)
risk_in_company

company_size
Enterprise    0.18
Large         0.18
Medium        0.18
Small         0.18
Startup       0.18
Name: layoff_risk, dtype: float64

In [197]:
# Insights : Layoff risk is uniform accross all company sizes(~0.18),indicating that layoffs are driven by external factors like 
# employee skills and market conditions rather than company size.

In [198]:
df['risk_in_exp'] = df.groupby('experience_level')['layoff_risk'].transform('mean').round(2)

In [199]:
risk_in_experience = df.groupby('experience_level')['layoff_risk'].mean().round(2).sort_values(ascending = False)
risk_in_experience

experience_level
Entry     0.38
Mid       0.18
Lead      0.08
Senior    0.08
Name: layoff_risk, dtype: float64

In [200]:
# Insights : Layoff risk decreases sharply from entry(0.38) to mid level(0.18) and stabilizes at senior levels(0.08),indicating that 
# higher experience, technical expertise and decision making responsibility reduces layoff risks.

# Work Culture Analysis

In [201]:
df.columns

Index(['country', 'job_role', 'ai_specialization', 'experience_level',
       'experience_years', 'salary', 'bonus', 'education_required', 'industry',
       'company_size', 'interview_rounds', 'year', 'work_mode', 'weekly_hours',
       'company_rating', 'job_openings', 'hiring_difficulty_score',
       'layoff_risk', 'ai_adoption_score', 'company_funding_billion',
       'economic_index', 'ai_maturity_years', 'offer_acceptance_rate',
       'tax_rate_percent', 'vacation_days', 'skill_demand_score',
       'automation_risk', 'job_security_score', 'career_growth_score',
       'work_life_balance_score', 'promotion_speed', 'cost_of_living_index',
       'employee_satisfaction', 'job_count', 'jobs_in_country',
       'jobs_in_industry', 'jobs_in_role', 'jobs_in_company', 'real_salary',
       'salary_country_avg', 'realsalary_by_country', 'salary_by_experience',
       'salary_by_specialization', 'salary_in_company_size',
       'promotion_speed_industry', 'satisfaction_by_exp',
       'workload_by_experience', 'layoff_risk_in_industry',
       'automation_risk_in_role', 'job_security_in_role', 'risk_in_company',
       'risk_in_exp'],
      dtype='object')

In [202]:
df[['salary','employee_satisfaction']].corr()

                        salary  employee_satisfaction
salary                 1.00000                0.62903
employee_satisfaction  0.62903                1.00000

In [203]:
# Insights : A Moderate correlation between salary and employee satisfaction indicating as salary increase , satisfaction increase.
# However moderate correlation,suggests that  other factors also influence employee satisfaction.

In [204]:
df['wlb_in_country'] = df.groupby('country')['work_life_balance_score'].transform('mean').round(2)

In [205]:
wlb_in_country = df.groupby('country')['work_life_balance_score'].mean().round(2).sort_values(ascending = False)
wlb_in_country

country
Singapore      69.53
Netherlands    69.40
Brazil         69.23
Germany        69.21
Japan          69.16
UAE            69.16
France         69.07
India          69.07
Canada         69.02
Australia      68.98
UK             68.96
USA            68.96
Name: work_life_balance_score, dtype: float64

In [206]:
# Insights : Work life balance score are highly consistent across countries,ranging from 69.53 to 68.96, with a very minimal variation.
# While Singapore and Netherlands are rank slightly higher and the UK,USA and Australia slightly lower.

In [207]:
df[['weekly_hours','employee_satisfaction']].corr()

                       weekly_hours  employee_satisfaction
weekly_hours               1.000000              -0.340942
employee_satisfaction     -0.340942               1.000000

In [208]:
# Insights : A weak to moderate negative correlation(-0.34) between working hours and employee satisfaction , suggests thatlonger working hours 
# are associated with lower satisfaction.However due to moderate strength, other factors such as salary and job security, also play significant role.

In [209]:
df['satisfaction_in_role'] = df.groupby('job_role')['employee_satisfaction'].transform('mean').round(2)

In [210]:
satisfaction_in_role = df.groupby('job_role')['employee_satisfaction'].mean().round(2).sort_values(ascending = False)
satisfaction_in_role

job_role
Research Scientist           74.08
Machine Learning Engineer    73.28
Computer Vision Engineer     73.18
NLP Engineer                 73.14
AI Engineer                  72.92
Software Engineer AI         72.75
Data Scientist               72.41
Data Analyst                 70.03
Name: employee_satisfaction, dtype: float64

In [211]:
# Insights : Job satisfaction varies moderately across roles(74.08 - 70.03),with Research Scientists reporting the highest and Data Analysts the 
# lowest.This variation  may reflect difference in factors such as employee compensation,workload and work life balance.

In [212]:
satisfaction_in_company = df.groupby('company_size')['employee_satisfaction'].mean().round(2).sort_values(ascending = False)
satisfaction_in_company

company_size
Enterprise    74.64
Medium        73.23
Small         73.11
Large         73.06
Startup       69.62
Name: employee_satisfaction, dtype: float64

In [213]:
# Insights : Employee satisfaction varies moderately across company size(74.64 - 69.62), with Enterprises reporting the highest satisfaction and startups 
# the lowest. This variation may reflect differences in factors such as work load,compensation and work life balance.

In [214]:
satisfaction_in_exp = df.groupby('experience_level')['employee_satisfaction'].mean().round(2).sort_values(ascending = False)
satisfaction_in_exp

experience_level
Lead      78.36
Senior    74.61
Mid       70.75
Entry     67.13
Name: employee_satisfaction, dtype: float64

In [215]:
# Insights : Employee satisfaction increases significantly with experience ranging from 67.13(Entry level) to 78.36(lead level).
# Lead reports the highest while entry level report the lowest satisfaction, indicating a strong positive relationship between 
# experience and satisfaction. This pattern may reflect differences in factors such as work load,compensation and work life balance.

In [216]:
df.to_csv('Global AI Career Insights.csv', index = False)